name: patapata_apps_flyer
description: This package is a plugin for Patapata that adds support for AppsFlyer to your Patapata app.
version: 1.0.0
publish_to: none
homepage: https://github.com/gree/patapata
repository: https://github.com/gree/patapata/tree/main/packages/patapata_apps_flyer

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  patapata_core: ^1.4.0

  appsflyer_sdk: ^6.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: PatapataAppsFlyerPlugin
