name: patapata_adjust
description: This package is a plugin for Patapata that adds support for Adjust to your Patapata app.
version: 1.0.0
publish_to: none
homepage: https://github.com/gree/patapata
repository: https://github.com/gree/patapata/tree/main/packages/patapata_adjust

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

  patapata_core: ^1.1.0

  adjust_sdk: ^4.38.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  plugin:
    platforms:
      android:
        package: dev.patapata.patapata_adjust
        pluginClass: PatapataAdjustPlugin
      ios:
        pluginClass: PatapataAdjustPlugin
