name: patapata_firebase_analytics
description: This package is a plugin for Patapata that adds support for Firebase Analytics to your Patapata app.
version: 1.1.0
homepage: https://github.com/gree/patapata
repository: https://github.com/gree/patapata/tree/main/packages/patapata_firebase_analytics

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  patapata_core: ^1.1.0

  patapata_firebase_core: ^1.1.0

  firebase_analytics: ^10.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
