name: patapata_firebase_auth
description: This package is a plugin for Patapata that adds support for Firebase Authentication to your Patapata app.
version: 1.2.2
homepage: https://github.com/gree/patapata
repository: https://github.com/gree/patapata/tree/main/packages/patapata_firebase_auth

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  patapata_core: ^1.4.0

  patapata_firebase_core: ^1.3.1

  firebase_auth: ^5.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
