name: patapata_sentry
description: This package is a plugin for Patapata that adds support for Sentry to your Patapata app.
version: 1.2.2
homepage: https://github.com/gree/patapata
repository: https://github.com/gree/patapata/tree/main/packages/patapata_sentry

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  patapata_core: ^1.4.0

  sentry_flutter: ^7.9.0
  sentry: ^7.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
