name: patapata_firebase_core
description: This package is a plugin for Patapata that adds support for Firebase to your Patapata app.
version: 1.3.1
homepage: https://github.com/gree/patapata
repository: https://github.com/gree/patapata/tree/main/packages/patapata_firebase_core

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  patapata_core: ^1.4.0

  firebase_core: ^3.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
