name: patapata_riverpod
description: This package is a plugin for Patapata that adds support for Riverpod to your Patapata app.
version: 1.3.0
homepage: https://github.com/gree/patapata
repository: https://github.com/gree/patapata/tree/main/packages/patapata_riverpod

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  patapata_core: ^1.4.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.1
  build_runner: ^2.4.9
  custom_lint: ">=0.6.4 <0.8.0"
  riverpod_lint: ^2.3.10

flutter:
