name: patapata_karte_core
description: This package is a plugin for Patapata that adds support for Karte to your Patapata app.
version: 1.0.0
publish_to: none
homepage: https://github.com/gree/patapata
repository: https://github.com/gree/patapata/tree/main/packages/patapata_karte_core

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter

  patapata_core: ^2.0.0

  karte_core: ^1.2.1
  karte_in_app_messaging: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.patapata.patapata_karte_core
        pluginClass: PatapataKarteCorePlugin
      ios:
        pluginClass: PatapataKarteCorePlugin
